15: Tests
Xoroma/java-shareit pull request #3
Opened 2023-05-21 16:17 UTC by Xoroma

2023-05-25 08:29 UTC, db-exp requested changes

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exception/BadRequestException.java
> +public class BadRequestException extends Exception {
Runtime - правильно

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exception/ExceptionsHandler.java
> +    @ExceptionHandler(NullPointerException.class)
NPE не нужно обрабатывать - его нужно не допускать.
Давай уберем и поправим там, где он возникает

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final UserRepository userRepository;
а зачем снова на репозитории перешел? хорошо же было с сервисами

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto addItem(ItemDto dto, long ownerId) throws NotFoundException {
как уже написал в исключениях - лучше наследовать от Runtime и не пробрасывать везде throws

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                               @RequestParam(required = false, defaultValue = "10")
тут лучше тоже Min, иначе можно получить ArithmeticException

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
>  public interface ItemRepository extends JpaRepository<Item, Long> {
не хватает аннотации Repository

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
не хватает аннотации Repository

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
>  public interface UserRepository extends JpaRepository<User, Long> {
не хватает аннотации Repository

2023-05-25 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                       @RequestParam(required = false, defaultValue = "1")
Min хорошо бы добавить

2023-05-25 08:29 UTC, db-exp commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +	UserRepository userRepository;
лучше использовать что-то одно - выше уже есть UserService

2023-05-26 21:13 UTC, Xoroma commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final UserRepository userRepository;
Можно я учту на будущее? А то тесты по покрытию не проходят, если переделать.

2023-05-27 18:30 UTC, db-exp requested changes

2023-05-27 18:30 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throws NotFoundException, BadRequestException {
переделай, пожалуйста, исключения на непроверяемые

2023-05-28 13:14 UTC, db-exp approved these changes

2023-06-04 09:55 UTC, merged